#!/bin/bash

VERSION=7.1.5
SWIPL_DIR="pl-$VERSION"
SWIPL_TAR="$SWIPL_DIR.tar.gz"
SWIPL_URL="http://www.swi-prolog.org/download/devel/src/$SWIPL_TAR"

# functions
msg() {
    echo -e "\033[1;32m-->\033[0m $0:" $*
}


# download tarball if needed
if [ ! -e "$SWIPL_TAR" ]; then
    msg "Downloading SWI-Prolog v$VERSION"
    curl --silent "$SWIPL_URL" > "$SWIPL_TAR"
fi

# build SWI-Prolog
msg "Compiling SWI-Prolog v$VERSION"
rm -rf "$SWIPL_DIR"
tar xzf "$SWIPL_TAR"
cd "$SWIPL_DIR"
cp ../swipl-build build
./build

# create tar ball of build artifacts
msg "Building tarball"
cd
tar czf "swi-prolog-on-dotcloud-$VERSION.tar.gz" swipl

msg "Starting simple HTTP server"
exec python -m SimpleHTTPServer "$PORT_WWW"
